ENV=develop
REPLICAS=2
vpc_cidr="10.1.0.0/16"
subnet_a_cidr="10.1.1.0/24"
subnet_b_cidr="10.1.2.0/24"
subnet_c_cidr="10.1.3.0/24"
arn_cluster_policy="arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
arn_worker_policy_list=["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy","arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly","arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]
node_desired_size=3
node_max_size=3
node_min_size=3
instance_type="t2.micro"
cluster_policy_name="AmazonEKSClusterPolicy"
arn_worker_policy_list=["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy", "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly", "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]